apiVersion: batch/v1
kind: Job
metadata:
  name: pw
spec:
  completions: 5
  parallelism: 5
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: pw-worker
        image: aaronsmits/pw-k8s:latest
        command:
        - "bash"
        - "-c"
        - |
          shard=$((JOB_COMPLETION_INDEX+1))
          npx playwright test--workers=1 --repeat-each=10
      restartPolicy: Never
