apiVersion: batch/v1
kind: Job
metadata:
  name: pw
spec:
  completions: 25
  parallelism: 25
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 120
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: pw-worker
        image: aaronsmits/pw-k8s:latest
        command:
        - "bash"
        - "-c"
        - |
          shard=$((JOB_COMPLETION_INDEX+1))
          npx playwright test --workers=1 --repeat-each=25 --shard=$shard/25
      restartPolicy: OnFailure
     
