apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-results-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: test-results-pv