apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-acct
  namespace: argo
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - eventsources
  - sensors
  - workflows
  - workfloweventbindings
  - workflowtemplates
  - clusterworkflowtemplates
  - cronworkflows
  - cronworkflows
  - workflowtaskresults
  verbs:
  - get
  - list
  - watch